import '../globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import ToasterProvider from '../providers/ToasterProvider'
import Provider from '../providers/AuthProvider'
/* import getCurrentUser from '../actions/getCurrentUser' */

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Admania.',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
/*   const currentUser = await getCurrentUser(); */

  return (
    <html lang="en">
      <body className={inter.className}>
      <Provider>
        <ToasterProvider />
            {children}
        </Provider>
      </body>
    </html>
  )
}
