import Navbar from '@/components/user/navbar/Navbar'
import '../globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import RegisterModal from '@/components/user/modals/RegisterModal'
import ToasterProvider from '../providers/ToasterProvider'
import LoginModal from '@/components/user/modals/LoginModal'
import Provider from '../providers/AuthProvider'
import getCurrentUser from '../actions/getCurrentUser'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Postamania.',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const currentUser = await getCurrentUser();

  return (
    <html lang="en">
      <body className={inter.className}>
      <Provider>
        <ToasterProvider />
        <LoginModal currentUser={currentUser}/>
        <RegisterModal />
        <Navbar currentUser={currentUser}/>
          <div className='pb-20 pt-28'>
            {children}
          </div>
        </Provider>
      </body>
    </html>
  )
}
